// This file is required by karma.conf.js and loads recursively all the .spec and framework files
// This file is auto-generated by scripts/generate-test-imports.js
// Run: node scripts/generate-test-imports.js

import 'zone.js/testing';
import { getTestBed } from '@angular/core/testing';
import {
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting
} from '@angular/platform-browser-dynamic/testing';

// First, initialize the Angular testing environment.
getTestBed().initTestEnvironment(
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting(),
  {
    teardown: { destroyAfterEach: false }
  }
);

// Then we find all the tests.
// Webpack 5 doesn't support require.context, so we import all spec files explicitly
// Auto-generated imports:
import './app/app.component.spec';
import './app/pages/home/home.component.spec';
import './app/shared/cart/cart.spec';
import './app/shared/form/form.component.spec';
